services:
  traefik:
    image: traefik:v2.10
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/data/
      - --entrypoints.web.address=:80
    ports:
      - 80:80
      - 443:443
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.$GATEWAY_HOST`)
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.services.traefik.loadbalancer.server.port=8080
    expose:
      - 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik-data:/data
    restart: unless-stopped
    networks:
      - stack-test

networks:
  stack-test:
    external: true
