services:
  typebot-db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - ./typebot-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
    expose:
      - 5432
    networks:
      - growon

  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: unless-stopped
    depends_on:
      typebot-db:
        condition: service_healthy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: .env
    expose:
      - 3000
    networks:
      - growon
    labels:
      - traefik.enable=true
      - traefik.http.routers.typebotbuilder.rule=Host(`typebot.$GATEWAY_HOST`)
      - traefik.http.routers.typebotbuilder.entrypoints=web,websecure
      - traefik.http.routers.typebotbuilder.tls.certresolver=letsencrypt
      - traefik.http.services.typebotbuilder.loadbalancer.server.port=3000
      - traefik.http.routers.typebotbuilder.middlewares=authelia@docker

  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    depends_on:
      typebot-db:
        condition: service_healthy
    restart: unless-stopped
    env_file: .env
    expose:
      - 3000
    networks:
      - growon
    labels:
      - traefik.enable=true
      - traefik.http.routers.typebotviewer.rule=Host(`bot.$GATEWAY_HOST`)
      - traefik.http.routers.typebotviewer.entrypoints=web,websecure
      - traefik.http.routers.typebotviewer.tls.certresolver=letsencrypt
      - traefik.http.services.typebotviewer.loadbalancer.server.port=3000
      - traefik.http.routers.typebotviewer.middlewares=authelia@docker

networks:
  growon:
    external: true
