services:
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    restart: unless-stopped
    env_file: .env
    expose:
      - 9000
      - 9001
    volumes:
      - ./minio-data:/data
    networks:
      - stack-test
    labels:
      - traefik.enable=true

    # console
      - traefik.http.routers.s3.rule=Host(`s3.$GATEWAY_HOST`)
      - traefik.http.routers.s3.entrypoints=web
      - traefik.http.services.s3.loadbalancer.server.port=9000
      - traefik.http.routers.s3.service=s3

    # Api
      - "traefik.http.routers.minio.rule=Host(`minio.$GATEWAY_HOST`)"
      - "traefik.http.routers.minio.entrypoints=web"
      - "traefik.http.services.minio.loadbalancer.server.port=9001"
      - "traefik.http.routers.minio.service=minio"
  createbuckets:
    image: minio/mc
    networks:
      - stack-test
    depends_on:
      - minio
    restart: unless-stopped
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 minio minio123;
      /usr/bin/mc mb minio/typebot;
      /usr/bin/mc anonymous set public minio/typebot/public;
      exit 0;
      "

networks:
  stack-test:
    external: true
